arch:
    max_epochs: 50
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (384, 384)
    train:
        batch_size: 1
        dataset: ['Image']
        path: ['/content/Town01_formatted/image_2']
        split: ['{:04}']
        depth_type: ['']
        repeat: [1]
    validation:
        dataset: ['KITTI']
        path: ['/content/Town01_formatted/image_2']
        split: ['/content/Town01_formatted/train_split.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/content/Town01_formatted/image_2']
        split: ['/content/Town01_formatted/train_split.txt']
        depth_type: ['velodyne']
